Hw1
danilasimanok/ComputerDataProcessingAlgorithms pull request #2
Opened 2020-02-28 22:26 UTC by danilasimanok

2020-02-29 20:25 UTC, gsvgit requested changes

2020-02-29 20:25 UTC, gsvgit commented on hw1/draw_shortest_tree.bat
> +@echo off
Вероятно, я не совсем внятно выразился, но Ваша программа (на C#) должна возвращать pdf-файл. То есть вам из .net кода надо как-то вызвать graphviz.

2020-02-29 20:25 UTC, gsvgit commented on hw1/Tasks/UselessTest/MatrixTest.cs
> +            Assert.Throws<ArgumentException>(
Не самая хорошая тактика --- проверять в одном тесте сразу несколько вещей.

2020-02-29 20:25 UTC, gsvgit commented on hw1/Tasks/UselessTest/MatrixTest.cs
> +            invalid2 = new int[][] {
Как и тут. Один тест на один сценарий.

2020-02-29 20:25 UTC, gsvgit commented on hw1/Tasks/Useless/ResizeArray.cs
> +                T[] newContent = new T[this.content.Length * 3 / 2];
А откуда такой странный коэф. увеличения?

2020-02-29 20:25 UTC, gsvgit commented on hw1/Tasks/Pathfinder(joke)/GraphCreator.cs
> +                return (this.graph.Clone(), this.edgeCost);
А зачем клонировать граф?

2020-02-29 20:25 UTC, gsvgit commented on hw1/Tasks/Pathfinder(joke)/GraphCreator.cs
> +            for (i = 0; i < this.matrix.Length; ++i)
1) Есть метод, позволяющй сразу и вершины и ребро добавить.
2) почему бы не использовать представление, которое основано на матрице смежности?

2020-03-01 11:03 UTC, danilasimanok commented on hw1/Tasks/Useless/ResizeArray.cs
> +                T[] newContent = new T[this.content.Length * 3 / 2];
Не понимаю. Почему он неправильный?

2020-03-01 11:04 UTC, danilasimanok commented on hw1/Tasks/Pathfinder(joke)/GraphCreator.cs
> +                return (this.graph.Clone(), this.edgeCost);
Ну, граф -- приватное поле GraphCreator-а. Он клонируется, чтобы снаружи его не могли поменять.

2020-03-01 11:07 UTC, gsvgit commented on hw1/Tasks/Useless/ResizeArray.cs
> +                T[] newContent = new T[this.content.Length * 3 / 2];
Я не сказал, что неправильный. Просто странный.

2020-03-01 11:07 UTC, gsvgit commented on hw1/Tasks/Pathfinder(joke)/GraphCreator.cs
> +                return (this.graph.Clone(), this.edgeCost);
Выглядит как проблема в дизайне.

2020-03-01 11:15 UTC, danilasimanok commented on hw1/Tasks/Useless/ResizeArray.cs
> +                T[] newContent = new T[this.content.Length * 3 / 2];
Просто было нужно число, чтобы оно, умноженное на начальный размер, а потом округленное до целых, давало бы больше, чем начальный размер.

2020-03-01 11:17 UTC, gsvgit commented on hw1/Tasks/Pathfinder(joke)/GraphCreator.cs
> +                return (this.graph.Clone(), this.edgeCost);
Просто умножить на 3? Зачем на что-то делить?

2020-03-01 11:18 UTC, gsvgit commented on hw1/Tasks/Useless/ResizeArray.cs
> +                T[] newContent = new T[this.content.Length * 3 / 2];
Просто умножить на 3? Зачем делить на что-то?

2020-03-01 19:35 UTC, gsvgit requested changes

2020-03-01 19:35 UTC, gsvgit commented on hw1/Tasks/UselessTest/PathfinderTest.cs
> +        public void TestInvalidGraphCreation() {
Неплохо бы ещё тесты на крайние случаи: граф из одной вершины, граф без рёбер и тд. Нужен тест на  то, что генерация pdf работает: хотя бы проверить, что pdf создаётся там, где нужно и что размер не нулевой.

2020-03-01 19:35 UTC, gsvgit commented on hw1/Tasks/Pathfinder(joke)/Properties/launchSettings.json
> +{
Этот файл точно нужен? Выглядит как локальные настройки.

2020-03-01 19:35 UTC, gsvgit commented on hw1/Tasks/Pathfinder(joke)/Program.cs
>                  fs.Write(System.Text.Encoding.Default.GetBytes(dot));
Почему бы для работы с файлами (и не только здесь) не использовать более высокоуровневые методы типа такого: https://docs.microsoft.com/ru-ru/dotnet/api/system.io.file?view=netframework-4.8

2020-03-11 11:41 UTC, gsvgit requested changes
Ок. Всё ещё смущает клонирование графа и наличие странных файлов в репозитории.

2020-03-31 05:26 UTC, gsvgit requested changes

2020-03-31 05:26 UTC, gsvgit commented on hw1/Tasks/Useless/ResizeArray.cs
> +                throw new IndexOutOfRangeException("Индекс должен лежать в границах [0;" + this.count + "]. Дано " + i);
Текст сообщений должен бфть на английском.

2020-03-31 05:26 UTC, gsvgit commented on hw1/Tasks/UselessTest/PathfinderTest.cs
> +        public void TestExtremeCase1() {
Назовите тесты соответствующий образом: "ГрафИзОднойВершины" и т.д.

2020-03-31 05:26 UTC, gsvgit commented on hw1/Tasks/Pathfinder(joke)/PDFGenerator.cs
> +            using (Process process = new Process())
А если при запуске процесса что-то пойдёт не так, получим ли мы разумное сообщение об ошибке?

2020-03-31 05:26 UTC, gsvgit commented on hw1/Tasks/MatrixMultiplier/Program.cs
> +            String path1 = args[0],
А что, если количество аргументов неправильное?

2020-04-06 07:23 UTC, gsvgit approved these changes
Ок.  Зачтено.

2020-04-17 14:09 UTC, merged