Пытаюсь включить travis.
danilasimanok/ComputerDataProcessingAlgorithms pull request #7
Opened 2020-03-30 14:11 UTC by danilasimanok

2020-04-13 07:43 UTC, gsvgit requested changes

2020-04-13 07:43 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/Matrix.fs
> +            List.fold sr.Add sr.IdentityElement <| (List.map multiply <| List.zip row column)
Лучше прямой пайп использовать.

2020-04-13 07:43 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/Matrix.fs
> +        let rec checkLengths length list =
Что-то мне кажется, что это должно через какую-то стандартную функцию выражаться.

2020-04-13 07:43 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/Maybe.fs
> +    type MaybeBuilder () =
Вроде есть модуль Option. В нём всякие такие вещи объявлены уже.

2020-04-13 07:43 UTC, gsvgit commented on hw2/FsharpTasks/MatrixMultiplier/Program.fs
> +    let argsErr () = printfn "Not enough arguments."
Есть такая либа Argu: https://fsprojects.github.io/Argu/  Как раз чтобы не изобретать велосипеодв при обработке аргументов.

2020-04-13 07:43 UTC, gsvgit commented on hw2/CsharpTasks/TasksTest/MatrixMultiplierTest.cs
> +                new Natural[] {new Natural(1), new Natural(2), new Natural(3)},
Почему бы не написать функцию-обёртку, которая из обычного массива конструирует массив Natural. код срау компактнее станет.

2020-04-13 09:00 UTC, gsvgit requested changes

2020-04-13 09:00 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/Matrix.fs
> +﻿namespace Matrix
Не надо сразу и namespace и module

2020-04-13 09:00 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/Matrix.fs
> +            List.fold sr.Add sr.IdentityElement <| (List.map multiply <| List.zip row column)
```
a
|> f
|> g
```
```
List.zip row column
|> List.map multiply
|> List.fold sr.Add sr.IdentityElement
```

2020-04-13 09:00 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/Matrix.fs
> +            else Some <| Rows list
```Some (Rows x)```

2020-04-13 09:00 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/MatrixIO.fs
> +            _ -> None
Странный шаблон обработки ошибок.

2020-04-13 09:00 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/MatrixIO.fs
> +            _ -> None
```failwith```

2020-04-19 09:05 UTC, danilasimanok commented on hw2/FsharpTasks/Matrix/Maybe.fs
> +    type MaybeBuilder () =
Stackoverflow [сказал](https://stackoverflow.com/questions/7818277/is-there-a-standard-option-workflow-in-f), что такого нет.

2020-04-19 09:37 UTC, gsvgit commented
Угу. Просто не понятно, чем не устраивает то, что есть в модуле option. Там
есть всякие map, iter и и.д. обычно их хватает.
https://en.m.wikibooks.org/wiki/F_Sharp_Programming/Option_Types

https://sidburn.github.io/blog/2016/05/11/option-module

On Sun, Apr 19, 2020, 12:06 PM danilasimanok <notifications@github.com>
wrote:

> *@danilasimanok* commented on this pull request.
> ------------------------------
>
> In hw2/FsharpTasks/Matrix/Maybe.fs
> <https://github.com/danilasimanok/ComputerDataProcessingAlgorithms/pull/7#discussion_r410857238>
> :
>
> > @@ -0,0 +1,10 @@
>
> +﻿namespace Matrix
>
> +
>
> +module Maybe =
>
> +
>
> +    type MaybeBuilder () =
>
>
> Stackoverflow сказал
> <https://stackoverflow.com/questions/7818277/is-there-a-standard-option-workflow-in-f>,
> что такого нет.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/danilasimanok/ComputerDataProcessingAlgorithms/pull/7#discussion_r410857238>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQDPDPJA3PTUUGKIISLRNK5H5ANCNFSM4LWT2MIQ>
> .
>

2020-04-20 06:36 UTC, gsvgit requested changes

2020-04-20 06:36 UTC, gsvgit commented on hw2/FsharpTasks/APSP/Program.fs
> +            let! matrix = (fromRowsList << readRowsList id) msrc
Кажется, я понял, зачем Вам maybe. Для этого есть такая штука: railway programming (https://fsharpforfunandprofit.com/rop/). Есть специальная либа (а может и не одна) для работы в этом стиле: https://fsprojects.github.io/Chessie/ Лучше тогда её использовать.

2020-04-20 06:36 UTC, gsvgit commented on hw2/FsharpTasks/TransitiveClosure/Program.fs
> +            let startInfo =
А почему запускалка ДОТа не сделана переиспользуемой ещё на стороне C#?

2020-04-20 06:36 UTC, gsvgit commented on hw2/FsharpTasks/TransitiveClosure/DotGenerator.fs
> +﻿module DotGenerator
И почему генерилка ДОТ-файла не переиспользуется?

2020-05-08 16:42 UTC, gsvgit requested changes

2020-05-08 16:42 UTC, gsvgit commented on hw2/FsharpTasks/MatrixMultiplier/Program.fs
> +﻿open FsMatrix.Matrix
А зачем много однотипных точек входа? Кажется, вполне можно сделать одну (может с дополнительным параметром, который говорит, что именно считаем) и весь код будет переиспользован.

2020-05-08 16:42 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/MatrixIO.fs
> +module MatrixIO =
А здесь правда наддо и модуль и неймспейс?

2020-05-08 16:42 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/Matrix.fs
> +    let floydWarshall sg matrix =
А почему Вы смешиваете стии именования переменных? Где-то ```newName```, а где-то ```new_name```. В .NET и в F# приянт первый стиль.

2020-05-10 06:56 UTC, danilasimanok commented on hw2/FsharpTasks/Matrix/MatrixIO.fs
> +module MatrixIO =
Да, т. к. в подключенных библиотеках тоже есть Matrix.

2020-05-10 07:05 UTC, danilasimanok commented on hw2/FsharpTasks/MatrixMultiplier/Program.fs
> +﻿open FsMatrix.Matrix
Не совсем понимаю, что нужно исправить. В смысле, сделать единственный ```Program```?

2020-05-10 07:26 UTC, gsvgit commented on hw2/FsharpTasks/MatrixMultiplier/Program.fs
> +﻿open FsMatrix.Matrix
Да. С общими параметрами и, как следствие, общим кодом, без дублирования.

2020-05-10 07:27 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/MatrixIO.fs
> +module MatrixIO =
Эм. И что? 1. Не понимаю, как это спасает от наличия матриц в других библиотеках. 2. Есть же полная квалификация имён.

2020-05-10 07:47 UTC, danilasimanok commented on hw2/FsharpTasks/Matrix/MatrixIO.fs
> +module MatrixIO =
Проблема в том, что у пространства имен одной подключенной библиотеки и модуля другой полностью совпадают названия. Поэтому, когда я прошу ```open Matrix```, мне открывают не те ```Matrix```.

2020-05-10 08:56 UTC, gsvgit commented on hw2/FsharpTasks/Matrix/MatrixIO.fs
> +module MatrixIO =
Ух. Звучит как проблема дизайна. Ну ладно. Хотя, по-хорошему, надо просто навести порядок в пространствах имён.

2020-05-10 09:51 UTC, gsvgit requested changes

2020-05-10 09:51 UTC, gsvgit commented on hw2/FsharpTasks/MatrixProcessor/Program.fs
> +            let readMatrix = fromRowsList << readRowsList int
То же, что и на [30 строке] (https://github.com/danilasimanok/ComputerDataProcessingAlgorithms/pull/7/files#diff-0a99e8c2e4206da3ab29ae1f310ca3ddR30). Вообще кажется, что код в разных кейсах можно достаточно сильно обобщить.

2020-05-10 09:51 UTC, gsvgit commented on hw2/FsharpTasks/MatrixProcessor/Args.fs
> +type Task =
А зачем выделять? Вроде как только в одном месте используются все эти типы. Пусть там и будут.

2020-05-10 09:51 UTC, gsvgit commented on hw2/FsharpTasks/MatrixProcessor/Program.fs
> +    else ()
А  правда этот ```else``` нельзя убратьт?

2020-05-10 10:43 UTC, gsvgit approved these changes

2020-05-10 11:03 UTC, merged