Hw3
danilasimanok/ComputerDataProcessingAlgorithms pull request #8
Opened 2020-05-12 14:49 UTC by danilasimanok

2020-05-12 15:57 UTC, gsvgit requested changes
Исправляйте генераторы. Часть про C# можно выкинуть. Дальше уже про параллельные вычисления.

2020-05-12 15:57 UTC, gsvgit commented on README.md
> +## Зпнятия
Занятия

2020-05-12 15:57 UTC, gsvgit commented on hw3/FsharpTasks/MatrixGenerator/Program.fs
> +            Seq.iter (fun x -> writeRowsList string (randomLists randomReal size) (path + string x)) range
Я бы ```Seq.iter``` вынес наверх, и только генератор варировал в зависимости от типа элемента.

2020-05-13 14:16 UTC, gsvgit requested changes

2020-05-13 14:16 UTC, gsvgit commented on hw3/Tasks/MatrixGenerator/Program.fs
> +            | REAL -> writeRowsList string (randomLists randomReal size) (path + string x)
Так и эти вызовы могут быть обобщены. У Вас в них одинаков восё, кроме того, какой рандом использовать.

2020-05-13 14:16 UTC, gsvgit commented on hw3/Tasks/MatrixGenerator/Program.fs
> +        let path = path + sep + (toString elementType) + sep + (string size)
Для работы с путями используйте System.IO.Path и другие пространства из  System.IO. Так никогда не перепутаете разделители (а то вдруг они платформозафисимы) и так далее.

2020-05-13 14:19 UTC, danilasimanok commented on hw3/Tasks/MatrixGenerator/Program.fs
> +            | REAL -> writeRowsList string (randomLists randomReal size) (path + string x)
Их я не знаю, как обобщить. У функций ```randomRea```l, ```randomBoolean``` и т. д. разные типы. Они все подходят под ```(unit -> 'a)```, но сделать такую функцию, которая бы их обобщала, у меня не вышло.

2020-05-13 14:24 UTC, danilasimanok commented on hw3/Tasks/MatrixGenerator/Program.fs
> +        let path = path + sep + (toString elementType) + sep + (string size)
А что сейчас не верно? Пользователь введет платформозависимый путь, который соединится с ```sep```, который тоже платформозависимый, но определится верно автоматически, и все заработает.
Или нужно из ввода пользователя сделать ```Path```, а потом его ```Combine```?

2020-05-13 14:28 UTC, gsvgit commented on hw3/Tasks/MatrixGenerator/Program.fs
> +        let path = path + sep + (toString elementType) + sep + (string size)
Нк да, а то Вы фактически преизобрели Path.Combine.

2020-05-13 14:31 UTC, gsvgit commented on hw3/Tasks/MatrixGenerator/Program.fs
> +            | REAL -> writeRowsList string (randomLists randomReal size) (path + string x)
А где проблемы с решением вида 
```
f g = writeRowsList string (randomLists g size) (path + string x)
...

 match elementType with
| REAL -> f randomReal
| ....

```

?

2020-05-13 15:13 UTC, danilasimanok commented on hw3/Tasks/MatrixGenerator/Program.fs
> +            | REAL -> writeRowsList string (randomLists randomReal size) (path + string x)
Типовыводилка протестует: после того, как я применяю ```f``` к ```extendedReal```, она решает, что тип ```f``` -- ```(unit -> float) -> int -> unit```. Указать явно, что ```g``` типа ```unit ->'a```, не помогает.
И еще там была у меня ошибка: для ```ExtendedReal``` надо вызывать ```writeRowsList toWord```, а не ```writeRowsList string```.

2020-05-13 15:22 UTC, gsvgit commented on hw3/Tasks/MatrixGenerator/Program.fs
> +            | REAL -> writeRowsList string (randomLists randomReal size) (path + string x)
Логично. Ладно, пусть так остаётся.

2020-05-13 15:32 UTC, gsvgit approved these changes

2020-05-13 15:32 UTC, merged