hw4
danilasimanok/ComputerDataProcessingAlgorithms pull request #9
Opened 2020-05-16 20:07 UTC by danilasimanok

2020-05-17 13:37 UTC, gsvgit requested changes
Вроде всё хорошо, но есть ощущение, что точка входа дублирует уже созданный ранее код.

2020-05-17 13:37 UTC, gsvgit commented on hw4/Tasks/MatrixMultiplier/Program.fs
> +type Args =
Где-то я подобный код уже видел.

2020-05-21 13:24 UTC, danilasimanok commented on hw4/Tasks/MatrixMultiplier/Program.fs
> +type Args =
Да, похожее описание аргументов командной строки когда-то было в hw2, но в последствие изменилось.

2020-05-21 13:48 UTC, gsvgit commented on hw4/Tasks/MatrixMultiplier/Program.fs
> +type Args =
Ну то есть нормально объединить их не представляется возможным?

2020-05-21 15:14 UTC, danilasimanok commented on hw4/Tasks/MatrixMultiplier/Program.fs
> +type Args =
Наверное, нет: в hw2 есть лишний обязательный параметр (задача).

2020-05-22 07:52 UTC, gsvgit commented on hw4/Tasks/MatrixMultiplier/Program.fs
> +type Args =
Ок. Тогда mailbox processor остался.

2020-06-03 12:03 UTC, gsvgit requested changes
1) Очень много вопросов к архитектуре. Постарался их локально в комментариях указать
2) Есть вопросы по дублированию кода.

Ещё предлагаю убрать 7 задание. ГПУ отдельно надо сделать. Запихивать в мейлбокс не надо. Но в текущем 8-м надо всё же провести анализ тех реализаций, которые есть: последовательное, параллельное на ЦПУ, параллельное на ГПУ, масштабируемость мейлбоксПроцессоров.

2020-06-03 12:03 UTC, gsvgit commented on hw4/Tasks/Actors/Semigroups.fs
> +﻿module Semigroups
А зачем здесь ещё одна копия полугрупп? Раньше ведь уже где-то было.

2020-06-03 12:03 UTC, gsvgit commented on hw4/Tasks/Actors/TransitiveClosure.fs
> +    let boolTRC = MailboxProcessor<TransitiveClosureMessage<bool>>.Start (processMail booleanSemigroup)
А транзитивное замыкание прям для всех типов матриц работает?

Вообще, данное решение с записью со всеми агентами получается нерасширяемым. Вы не можете взять и убрать или добавть ещё один тип матриц. Вы жёстко прибили гвоздями тот факт, что у Вас 4 строго заданных типа. Это касается всех процессоров.

2020-06-03 12:03 UTC, gsvgit commented on hw4/Tasks/MatrixProcessor/Program.fs
> +            let killEveryone () =
Вообще говоря, странно, что Вы всех явно останавливаете. У Вас есть только одно ограничение: количество матриц на входе. Вот когда всё вончилось, тогда все и должны умереть.

2020-06-03 13:56 UTC, danilasimanok commented on hw4/Tasks/Actors/Semigroups.fs
> +﻿module Semigroups
Раньше была только полугруппа boolean: в hw2 она определялась в функции main.

2020-06-03 13:58 UTC, danilasimanok commented on hw4/Tasks/MatrixProcessor/Program.fs
> +            let killEveryone () =
Я останавливаю всех тогда, когда в процессе вычислений возникли ошибки, либо когда дана команда EXIT.

2020-06-03 14:23 UTC, gsvgit commented on hw4/Tasks/MatrixProcessor/Program.fs
> +            let killEveryone () =
Так а ошибки не должны ведь приводить к остановке. Ну не посчиталась одна задача, есть ещё много других, которые посчитаются.

А вот команда EXIT --- это интересно. Она снаружи подаётся? Опять же, Вы её подаёте только корневому агенту. В идеале Вы даже не знаете, сколько у него дополнительно процессоров запущено.

2020-06-03 14:24 UTC, gsvgit commented on hw4/Tasks/Actors/Semigroups.fs
> +﻿module Semigroups
А. Ну тогда выносите это всё в общее место. И тогда оно вряд ли с Акторами будет связано.

2020-06-03 14:33 UTC, danilasimanok commented on hw4/Tasks/MatrixProcessor/Program.fs
> +            let killEveryone () =
Да, но другие задачи могут использовать результаты той, которая не посчиталась. Например
m = READ BOOL file_with_error
m' = TRC m
EXIT

2020-06-03 14:35 UTC, danilasimanok commented on hw4/Tasks/MatrixProcessor/Program.fs
> +            let killEveryone () =
Да, команда EXIT подается снаружи, попадает в корень, корень ее рассылает всем остальным и ждет, пока они сообщат, что закончили, после умирает и присылает сообщение об этом в main. Получив это сообщение, main завершается.

2020-06-03 14:41 UTC, gsvgit commented
Угу. Просто по коду кажется, что Вы там ракету в соседнюю галактику
запускаете, не меньше.

Regards,
Semyon Grigorev.


ср, 3 июн. 2020 г. в 17:36, danilasimanok <notifications@github.com>:

> *@danilasimanok* commented on this pull request.
> ------------------------------
>
> In hw4/Tasks/MatrixProcessor/Program.fs
> <https://github.com/danilasimanok/ComputerDataProcessingAlgorithms/pull/9#discussion_r434616423>
> :
>
> > +        readCommand ()
>
> +
>
> +type ControllerCommands =
>
> +    Start of exited : AsyncReplyChannel<bool>
>
> +
>
> +[<EntryPoint>]
>
> +let main _ =
>
> +    let creators = createCreators ()
>
> +    let readers = createReaders ()
>
> +    let writers = createWriters ()
>
> +    let multipliers = createMultipliers ()
>
> +    let transitiveClosures = createTransitiveClosures ()
>
> +    let processMail (inbox : MailboxProcessor<ControllerCommands>) =
>
> +        let replyChannel = match Async.RunSynchronously (inbox.Receive ()) with Start r -> r
>
> +        let rec innerLoop (matrices : Map<string, VariableInformation>) writeQueue  = async {
>
> +            let killEveryone () =
>
>
> Да, команда EXIT подается снаружи, попадает в корень, корень ее рассылает
> всем остальным и ждет, пока они сообщат, что закончили, после умирает и
> присылает сообщение об этом в main. Получив это сообщение, main завершается.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/danilasimanok/ComputerDataProcessingAlgorithms/pull/9#discussion_r434616423>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQABIOW22NCQMT3JMS3RUZNVJANCNFSM4NDB3XGQ>
> .
>

2020-09-15 06:00 UTC, gsvgit approved these changes
Ок. Осталась брама и финальные замеры, стало быть.

2020-09-16 07:35 UTC, merged